---
title: "A Collection of R Tutorials and Lessons"
author: "Danielle Quinn"
date: "November 6, 2015"
output: html_document
---
####[Lesson 1: Introduction to R and R Studio I](http://daniellequinn.github.io/RLessons/Lesson1/Lesson1.html)####

  - Using R as a calculator
  - Functions and arguments
  - Installing and loading packages
  - Objects in R
  - Data structures
  - Indexing
  - Factors

####[Lesson 2: Introduction to R and R Studio II](http://daniellequinn.github.io/RLessons/Lesson2/Lesson2.html)####

  - Importing data
  - Data frames
  - Indexing data frames
  - Handling dates using `lubridate`
  - Simple looping
  
####[Linear Models to GLMs](http://daniellequinn.github.io/RLessons/Models/LinearModels_to_GLMs/LinearModelsToGLMs.html)####
  - Linear models
  - Checking for heterogeneity
  - Poisson GLMs
  - Overdispersion
  - Model predictions
  - Adding factors and offsets
  - Negative binomial GLMs

####[Sensitivity Analysis](http://daniellequinn.github.io/RLessons/SensitivityAnalysis/SensitivityAnalysis.html)####

  - Oversampling
  - Identifying target/baseline values
  - Resampling
  - Bootstrapping
  - Calculating processing time required

####[Formatting Dates Using `lubridate`](http://daniellequinn.github.io/RLessons/FormattingDates/FormattingDates.html)####
  - Setting up data
  - Using `ymd()` and `ymd_hms()`
  - Time zones
  - Extracting date and time components
  - Time intervals
  - Leap years

####Mixed Effect Models (coming soon!)####
####Zero Inflated Models (coming soon!)####
####Occupancy and Detectability Models (coming soon!)####
####Tips and Tricks for Advanced `ggplot2` (coming soon!)####