---
title: "Formatting Dates Using lubridate"
author: "Danielle Quinn"
date: "Tuesday, November 03, 2015"
output: html_document
---

One of the most common issues that new (and experienced!) R users have is formatting dates both prior to data import and during analyses. The simplest approach to dealing with dates is to ensure that the flat file (csv or txt) that is being read into R contains a *separate column for each component of date and time*. So, if date is a variable in your dataset, convert the date to three separate columns (day, month, year) prior to import, and if date and time are variables, convert those to six separate columns (second, minute, hour, day, month, year).

If you're using Excel to prepare your data for import, you can use the `=YEAR()` function, for example, to extract the year value from a cell formatted as a date. *Note:* If you ever try this and it results in an obscure date like "1900-01-01", it means that you just need to format your year column differently. If you're stuck, here's a link to a good explanation of how to deal with this! <http://www.excelfunctions.net/YearFunction.html>

